### ISSUE TITLE
K čemu slouží var/{main.yml,srv.yml} ?

### ISSUE THREAD

**Issue by westfood** [NLCR/ansible-setserv#1]
K čemu slouží tohle?
```
ansible_serv_specific: "setApache"
```

**Comment by JanMeritus** [comment]
Ahoj, pockaj dnes do vecera, nez si precistim povodne verzie, toto je relikvia z minuleho vyvojoveho modulu, kde som mal setServ.yml, na dve, tu ich zlucujem, a bude sa to riadit len nastavenim vo varoch.

Zdravim,

Z.

**Comment by JanMeritus** [comment]
Odstranene v commite #1659b2d07702b53ddf2c5d7a98f7ab638fd1f8a5
